name: NoCheatPlus
version: 4.0.0-SNAPSHOT-Updated-${buildDescription}
description: Detect and fight the exploitation of various flaws/bugs in Minecraft.

author: NeatMonster
authors: [asofold, Evenprime, CaptainObvious0, xaw3ep]
website: https://github.com/Updated-NoCheatPlus/NoCheatPlus
dev-url: https://github.com/Updated-NoCheatPlus/NoCheatPlus

main: fr.neatmonster.nocheatplus.NoCheatPlus
api-version: 1.13
folia-supported: true

softdepend:
- ProtocolLib
- Carbon

commands:
    nocheatplus:
        aliases: [ncp]
        description: NoCheatPlus command(s).
        usage: |
               +------------------+
               | Commands Overview |
               +------------------+
               /ncp top (entries) (check/s...) (sort by...) - Display the top results of a given check.
               /ncp info (playername) - Violation summary for a player.
               /ncp inspect (playername) - Status info for a player.
               /ncp notify on|off - Toggle in-game notifications on/off.
               /ncp removeplayer (playername) [(check type)] - Clear a check's data for a given player.
               /ncp reload - Reload the configuration.
               /ncp lag - Lag-related info.
               /ncp version - Display information about both the server and the plugin.
               /ncp commands - List all commands, including auxiliary ones.
               /ncp stopwatch (start/stop/distance/return) [distance] - Simple command for measuring time and distances.
    sad:
        description: SadAC control command (redstone/entity/banned items)
        permission: nocheatplus.admin.sadac
        usage: /sad [lag|banitem|reload]

permissions:
    nocheatplus.admin:
        description: NoCheatPlus admin permission.
        default: op
    nocheatplus.admin.sadac:
        description: SadAC module admin permission.
        default: op
    nocheatplus.filter:
        description: Allow filtering commands from NCP logging.
        default: op
    nocheatplus.filter.command.nocheatplus:
        description: Filter the /ncp command from NCP logging.
        default: op
    nocheatplus.checks.blockbreak.reach.silent:
        description: Silent notifications for blockbreak reach check.
        default: false
    nocheatplus.checks:
        description: Wildcard for all check bypass permissions.
        default: false
